### ISSUE TITLE
git config

### ISSUE THREAD

**Issue by tim2CF** [tkachuk-labs/stack-templates#9]
Add additional optional git config arguments for nix shell
```shell
git config --global user.name "Your Name"
git config --global user.email "youremail@yourdomain.com"
```

**Comment by tim2CF** [comment]
GIT_AUTHOR_NAME is the human-readable name in the “author” field.

GIT_AUTHOR_EMAIL is the email for the “author” field.

GIT_AUTHOR_DATE is the timestamp used for the “author” field.

GIT_COMMITTER_NAME sets the human name for the “committer” field.

GIT_COMMITTER_EMAIL is the email address for the “committer” field.

GIT_COMMITTER_DATE is used for the timestamp in the “committer” field.

EMAIL is the fallback email address in case the user.email configuration value isn’t set. If this isn’t set, Git falls back to the system user and host names.

**Comment by 21it** [comment]
fixed in 
https://github.com/tkachuk-labs/stack-templates/commit/4c026e7667390c77be68e43e0d67df15204697d2
